name: Test
on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cat /etc/lsb-release
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Deduplicate dependencies
        run: yarn run yarn-deduplicate --fail --strategy fewer
      - name: Build
        run: yarn run build
      - name: Format
        run: yarn run prettier --check
      - name: Lint
        run: yarn run xo
      - name: Run Action
        uses: ./
        with:
          app_id: "1234"
          private_key: ${{ secrets.private_key }}
        continue-on-error: true
